#! /bin/bash
#Scripted by Sark Xing

#Change working directory
cd "$(dirname "$0")"

#Uninstall previous Eudic.app and restore preferences
echo "Removing Eudic..."
brew install wget
wget --no-check-certificate -q --show-progress --progress=bar:force 2>&1 https://github.com/sarkrui/Eudic-for-Mac/raw/master/eudicmac_3.8.2.dmg
hdiutil attach eudicmac_3.8.2.dmg

sudo chflags nouchg ~/Library/Preferences/com.eusoft.eudic.plist
sudo rm -r /Applications/Eudic.app
sudo rm -r /Applications/Eudb_en.app
sudo rm ~/Library/Preferences/com.eusoft.eudic.plist
sudo rm ~/Library/Cookies/com.eusoft.eudic.LightPeek.binarycookies
sudo rm ~/Library/Cookies/com.eusoft.eudic.binarycookies
sudo rm -r ~/Library/Saved\ Application\ State/com.eusoft.eudic.savedState
sudo rm -r ~/Library/Caches/com.eusoft.eudic
sudo rm -r ~/Library/Application\ Support/com.eusoft.eudic

#Install Eudic and replace plist
echo "Installing Eudic..."
sudo cp -R /Volumes/Eudic\ 欧路词典/Eudic.app /Applications/
sudo chflags nouchg ~/Library/Preferences/com.eusoft.eudic.plist
sudo rm ~/Library/Preferences/com.eusoft.eudic.plist
sudo cp com.eusoft.eudic.plist ~/Library/Preferences/
sudo chflags uchg ~/Library/Preferences/com.eusoft.eudic.plist

#下载牛津高阶词典
	while true; do
    	read -p "你想要下载牛津高阶词典吗？(Y/N)" yn
    	case $yn in
        	[Yy]* ) 
				echo "正在下载词典文件..."
				wget --no-check-certificate -q --show-progress --progress=bar:force 2>&1 https://github.com/sarkrui/Eudic-for-Mac/releases/download/1.0.1/Oxford_mdict.zip
				unzip Oxford_mdict.zip
				echo "安装词典文件..."
				sudo cp  Oxford_mdict/O8C.* ~/Library/Eudb_en/

			break;;
        	[Nn]* ) 

echo "Done."
echo "Enjoy it!"